FROM stoo/erlang

RUN ln -s erlang-17.1 /opt/erlang
RUN ln -s /opt/erlang/bin/* /usr/local/bin/


ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y curl

# Install additional packages
RUN apt-get install -y less
RUN apt-get install -y man
RUN apt-get install -y unixodbc
RUN apt-get install -y libssl1.0.0
#RUN apt-get install -y libwxgtk2.8-0

RUN apt-get install -y make
RUN apt-get install -y --reinstall openssh-server
RUN ssh-keygen -q -t rsa -f /root/.ssh/id_rsa -N ""
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
RUN echo "root:root" | chpasswd
RUN apt-get install -y host
RUN apt-get install -y git
RUN apt-get install -y wget

#RUN groupadd -r users -g 433
RUN mkdir -p /home/$USER
RUN useradd -u $USERID -r -g users -d /home/$USER -s /bin/bash -c "Docker image user" $USER
RUN chown -R $USER:users /home/$USER
RUN mkdir -p /home/$USER/.ssh
RUN ssh-keygen -q -t rsa -f /home/$USER/.ssh/id_rsa -N ""
RUN cp /home/$USER/.ssh/id_rsa.pub /home/$USER/.ssh/authorized_keys
RUN echo "$USER:$USER" | chpasswd

ADD ./init-container /init-container
EXPOSE 22
CMD ["/init-container", "$USER"]

